/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FirstProj;

 import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
   public void testFound() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4,5,6,7,13,24,67));
      assertTrue(App.search(array, 4,2,5));
    }

    @Test
    public void testNotFound() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4,5,6,7,13,24,67));
      assertFalse(App.search(array, 5,1,3));
    }

    @Test
    public void testEmptyArray() {
      ArrayList<Integer> array = new ArrayList<>();
      assertFalse(App.search(array, 1,2,5));
    }

    @Test
    public void testNull() {
      assertFalse(App.search(null, 1,5,7));
    }
      @Test
   public void testNegativeStart() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4,5,6,7,13,24,67));
      assertFalse(App.search(array, 4,-2,5));
    }

}
