/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FirstProj;

import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
       public static boolean search(ArrayList<Integer> array, int e,int start,int end) {
        System.out.println("inside search");
        if (start < 0) return false;
        if (array == null) return false;
        if(array.size()==0)return false;
        if(array.indexOf(e)>=start&&array.indexOf(e)<=end)
        return true;
        return false;
      }
}
